# Generated by Django 3.2.6 on 2021-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_profile_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
