# Generated by Django 3.2.6 on 2024-08-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_profile_verification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='final_submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
