# Generated by Django 3.2.6 on 2021-08-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_target', models.CharField(max_length=20)),
                ('school_index', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=40)),
                ('f_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Father's Name")),
                ('m_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Mother's Name")),
                ('g_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('g_name', models.CharField(blank=True, max_length=40, null=True, verbose_name="Guardian's Name")),
                ('sex', models.CharField(max_length=1, verbose_name='Gender')),
                ('religion', models.CharField(max_length=1)),
                ('caste', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.CharField(max_length=10, verbose_name='Date of Birth')),
                ('fl', models.CharField(max_length=2, verbose_name='First Language')),
                ('sl', models.CharField(max_length=2, verbose_name='Second Language')),
                ('opt', models.CharField(blank=True, max_length=2, null=True, verbose_name='Optional Elective')),
                ('serial', models.CharField(max_length=4)),
                ('edited', models.BooleanField(default=False)),
                ('dob_edited', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('not_selected', models.BooleanField(default=False)),
                ('school_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.profile')),
            ],
            options={
                'ordering': ('-serial',),
            },
        ),
    ]
