# Generated by Django 3.2.6 on 2021-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_remove_student_school_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("serial",)},
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("", "Pending"), ("1", "Selected"), ("2", "Not Selected")],
                max_length=1,
                null=True,
            ),
        ),
    ]
