# Generated by Django 3.2.6 on 2021-08-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210813_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='not_selected',
        ),
        migrations.RemoveField(
            model_name='student',
            name='selected',
        ),
    ]
