# Generated by Django 3.2.6 on 2021-08-13 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_auto_20210813_1139"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="dob_edited",
        ),
    ]
