# Generated by Django 3.2.6 on 2021-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_alter_supportdocument_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Date of Birth"
            ),
        ),
    ]
