# Generated by Django 3.2.6 on 2022-06-19 06:12

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0009_alter_student_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=student.models.profile_upload_path
            ),
        ),
    ]
