# Generated by Django 3.2.6 on 2024-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_profile_pic_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='underage_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
